fixup! Fix deleteObject in history-preserving mode to conform to ZODB interface
Try to fix the following problem with MySQL:

Error in test test_check_refs_missing_after_prepack (relstorage.tests.testmysql.MySQLHistoryFreeTestPack_PyMySQL)
Traceback (most recent call last):
  File "C:\Python38-x64\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Python38-x64\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Python38-x64\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\projects\relstorage\src\relstorage\tests\packundo.py", line 238, in test_check_refs_missing_after_prepack
    missing = self._storage.pack(None, referencesf, check_refs=True, skip_prepack=True)
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 922, in pack
    result = pack.check_refs(referencesf)
  File "src\\perfmetrics\\metric.py", line 72, in perfmetrics._metric._AbstractMetricImpl.__call__
  File "c:\projects\relstorage\src\relstorage\storage\pack.py", line 223, in check_refs
    return self.packundo.check_refs(tid_int)
  File "c:\projects\relstorage\src\relstorage\adapters\packundo.py", line 325, in check_refs
    self.runner.run_script_stmt(ss_load_cursor, stmt)
  File "c:\projects\relstorage\src\relstorage\adapters\scriptrunner.py", line 81, in run_script_stmt
    cursor.execute(stmt, generic_params)
   - __traceback_info__:
                    SELECT zoid, to_zoid
                    FROM pack_object
                    INNER JOIN object_ref USING (zoid)
                    WHERE keep = TRUE
                    AND NOT EXISTS (
                        SELECT state FROM (
                            SELECT state
                            FROM object_state
                            WHERE object_state.zoid = to_zoid
                            AND object_state.tid = (
                                SELECT MAX(tid)
                                FROM object_state
                                WHERE object_state.zoid = to_zoid
                            )
                        ) t
                        WHERE state IS NOT NULL
                    )

  File "C:\Python38-x64\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Python38-x64\lib\site-packages\pymysql\cursors.py", line 415, in _query
    conn.query(q, unbuffered=True)
  File "C:\Python38-x64\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python38-x64\lib\site-packages\pymysql\connections.py", line 768, in _read_query_result
    result.init_unbuffered_query()
  File "C:\Python38-x64\lib\site-packages\pymysql\connections.py", line 1173, in init_unbuffered_query
    first_packet = self.connection._read_packet()
  File "C:\Python38-x64\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Python38-x64\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Python38-x64\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'to_zoid' in 'where clause'")