fixup! Fix deleteObject in history-preserving mode to conform to ZODB interface
Fix failure of test_exits_critical_section for history-preserving mode:

    Failure in test test_exits_critical_section (relstorage.storage.tpc.tests.test_vote.TestHistoryPreservingDeleteOnly)
    Traceback (most recent call last):
      File "C:\Python27-x64\lib\unittest\case.py", line 329, in run
        testMethod()
      File "c:\projects\relstorage\src\relstorage\storage\tpc\tests\test_vote.py", line 136, in test_exits_critical_section
        self._check_lock_and_move_commit(committed)
      File "c:\projects\relstorage\src\relstorage\storage\tpc\tests\test_vote.py", line 218, in _check_lock_and_move_commit
        self.assertFalse(committed)
      File "C:\Python27-x64\lib\unittest\case.py", line 416, in assertFalse
        raise self.failureException(msg)
    AssertionError: True is not false

I was originally running tests with --layer sqlite which does not include this
particular test - that's why it was missed.

Committed becomes true, because now deletions are committed the same way as
regular data records - only with data payload = NULL.