fixup! Fix deleteObject in history-preserving mode to conform to ZODB interface
Now try to fix the next problem with PostgreSQL:

Error in test test_check_refs_missing_after_prepack (relstorage.tests.testpostgresql.PostgreSQLHistoryFreeTestPack_psycopg2)
Traceback (most recent call last):
  File "C:\Python38-x64\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Python38-x64\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Python38-x64\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\projects\relstorage\src\relstorage\tests\packundo.py", line 238, in test_check_refs_missing_after_prepack
    missing = self._storage.pack(None, referencesf, check_refs=True, skip_prepack=True)
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 922, in pack
    result = pack.check_refs(referencesf)
  File "src\\perfmetrics\\metric.py", line 72, in perfmetrics._metric._AbstractMetricImpl.__call__
  File "c:\projects\relstorage\src\relstorage\storage\pack.py", line 223, in check_refs
    return self.packundo.check_refs(tid_int)
  File "c:\projects\relstorage\src\relstorage\adapters\packundo.py", line 320, in check_refs
    self.runner.run_script_stmt(ss_load_cursor, stmt)
  File "c:\projects\relstorage\src\relstorage\adapters\scriptrunner.py", line 81, in run_script_stmt
    cursor.execute(stmt, generic_params)
   - __traceback_info__:
                    SELECT zoid, to_zoid
                    FROM pack_object
                    INNER JOIN object_ref USING (zoid)
                    WHERE keep = TRUE
                    AND NOT EXISTS (
                        SELECT state FROM (
                            SELECT state, MAX(tid)
                            FROM object_state
                            WHERE object_state.zoid = to_zoid
                        ) t
                        WHERE state IS NOT NULL
                    )

psycopg2.errors.GroupingError: column "object_state.state" must appear in the GROUP BY clause or be used in an aggregate function
LINE 8:                             SELECT state, MAX(tid)
                                           ^